### ISSUE TITLE
[FEATURE] add CI

### ISSUE THREAD

**Issue by daidai21** [idealvin/co#146]

**Comment by idealvin** [comment]
@daidai21 

这东西最近老是发报错邮件，不知道什么情况..

**Comment by daidai21** [comment]
@idealvin 因为确实Ubuntu下编译单测有问题

**Comment by daidai21** [comment]
我mac os下拉最新的master分支代码编译错误

**Comment by idealvin** [comment]
我看看

**Comment by idealvin** [comment]
@daidai21 
用最新的 xmake 编译试试

```sh
xmake update
xmake c -a
xmake -a
```

**Comment by daidai21** [comment]
1. 你后边不是加了第三方库么，cmake依赖第三方库特别麻烦，然后cmake也没改，所以报错了。

2. xmake编译Ubuntu 16、18、20下我编译都没通过。

https://github.com/idealvin/co/blob/fc0a6c776e7f8e6de97322e59a41072af610c483/test/xmake.lua#L13-L19

https://github.com/idealvin/co/blob/fc0a6c776e7f8e6de97322e59a41072af610c483/test/so/http_cli.cc#L3

感觉这里是不是有问题呀，lua我不会。如果`HAS_LIBCURL`宏定义的的话需要加入依赖库`add_packages("libcurl")`

3. mac下可以跑通的 [link](https://github.com/daidai21/co/runs/2520463249?check_suite_focus=true)，用的xmake

4. 现在master和dev分支的cmake肯定是编译不了的。

5. OpenSSL只能是1.1.1版本的才能编译，其他版本会报错

要不得想办法搞好泛性和适配性， 要不把cpp.yml CI先删了算了

测试没问题的mac actions配置  [link](https://github.com/daidai21/co/actions/runs/818027705/workflow)

```yml
name: C/C++ CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  job_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install xmake
      run: bash <(curl -fsSL https://xmake.io/shget.text)
    - name: Update env & Check xmake installed & Compile libco
      run: |
        source ~/.xmake/profile
        xmake --version
        xmake update
        xmake c -a
        xmake -a
```

C++引入第三方库太麻烦了...
